CREATE TABLE T_NXT_EVENTO
  (
    ID_EVENTO NUMBER (2) NOT NULL ,
    DT_EVENTO DATE NOT NULL ,
    URL_FOTO  VARCHAR2 (512) NOT NULL ,
    DS_EVENTO VARCHAR2 (600) NOT NULL
  ) ;
ALTER TABLE T_NXT_EVENTO ADD CONSTRAINT T_NXT_EVENTO_PK PRIMARY KEY ( ID_EVENTO ) ;


CREATE TABLE T_NXT_PERSONAGEM
  (
    ID_PERSONAGEM    NUMBER (2) NOT NULL ,
    NM_PERSONAGEM    VARCHAR2 (64) NOT NULL ,
    NM_ATOR          VARCHAR2 (64) NOT NULL ,
    URL_FOTO         VARCHAR2 (512) NOT NULL ,
    DT_NASCIMENTO    DATE NOT NULL ,
    DS_APRESENTACAO  VARCHAR2 (600) NOT NULL ,
    NM_CLASSIFICACAO VARCHAR2 (32) NOT NULL
  ) ;
ALTER TABLE T_NXT_PERSONAGEM ADD CONSTRAINT T_NXT_PERSONAGEM_PK PRIMARY KEY ( ID_PERSONAGEM ) ;


CREATE TABLE T_NXT_PERSONAGEM_EVENTO
  (
    ID_PERSONAGEM        NUMBER (2) NOT NULL ,
    ID_EVENTO            NUMBER (2) NOT NULL ,
    DS_EVENTO_PERSONAGEM VARCHAR2 (4000) NOT NULL
  ) ;
ALTER TABLE T_NXT_PERSONAGEM_EVENTO ADD CONSTRAINT T_NXT_PERSONAGEM_EVENTO_PK PRIMARY KEY ( ID_PERSONAGEM, ID_EVENTO ) ;


ALTER TABLE T_NXT_PERSONAGEM_EVENTO ADD CONSTRAINT FK_EVENTO_PERS_EVENTO FOREIGN KEY ( ID_EVENTO ) REFERENCES T_NXT_EVENTO ( ID_EVENTO ) ;

ALTER TABLE T_NXT_PERSONAGEM_EVENTO ADD CONSTRAINT FK_PERSONAGEM_PERS_EVENTO FOREIGN KEY ( ID_PERSONAGEM ) REFERENCES T_NXT_PERSONAGEM ( ID_PERSONAGEM ) ;
